name: pooled_video_player
description: Efficient video playback with object pooling for short-form video feeds.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.1

dependencies:
  audio_session: ^0.2.2
  device_info_plus: ^10.1.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  # Temporary override to include texture rotation fix
  # https://github.com/media-kit/media-kit/issues/627
  # Will be removed once the fix is merged and released
  media_kit_video:
    git:
      url: https://github.com/divinevideo/media-kit
      ref: fix/texture-rotation
      path: media_kit_video

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0