name: hashtag_repository
description: Repository for searching hashtags via the Funnelcake API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  funnelcake_api_client:
  models:

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
